import type { tasks, growthPhases, timeEntries, dailyTimeLogs, categoryTargets, clients, recurringTasks, categories, weeklyPriorities, calendarEvents, calendarAccounts, calendarSubscriptions, calendarColorLabels, calendarProfiles } from "@/db/schema";
import type { InferSelectModel, InferInsertModel } from "drizzle-orm";

export type Task = InferSelectModel<typeof tasks>;
export type NewTask = InferInsertModel<typeof tasks>;
export type GrowthPhase = InferSelectModel<typeof growthPhases>;
export type NewGrowthPhase = InferInsertModel<typeof growthPhases>;
export type TimeEntry = InferSelectModel<typeof timeEntries>;
export type NewTimeEntry = InferInsertModel<typeof timeEntries>;
export type DailyTimeLog = InferSelectModel<typeof dailyTimeLogs>;
export type NewDailyTimeLog = InferInsertModel<typeof dailyTimeLogs>;
export type CategoryTarget = InferSelectModel<typeof categoryTargets>;
export type NewCategoryTarget = InferInsertModel<typeof categoryTargets>;
export type Client = InferSelectModel<typeof clients>;
export type NewClient = InferInsertModel<typeof clients>;
export type RecurringTask = InferSelectModel<typeof recurringTasks>;
export type NewRecurringTask = InferInsertModel<typeof recurringTasks>;
export type Category = InferSelectModel<typeof categories>;
export type NewCategory = InferInsertModel<typeof categories>;
export type WeeklyPriority = InferSelectModel<typeof weeklyPriorities>;
export type CalendarEvent = InferSelectModel<typeof calendarEvents>;
export type NewCalendarEvent = InferInsertModel<typeof calendarEvents>;
export type CalendarAccount = InferSelectModel<typeof calendarAccounts>;
export type NewCalendarAccount = InferInsertModel<typeof calendarAccounts>;
export type CalendarSubscription = InferSelectModel<typeof calendarSubscriptions>;
export type NewCalendarSubscription = InferInsertModel<typeof calendarSubscriptions>;
export type CalendarColorLabel = InferSelectModel<typeof calendarColorLabels>;
export type CalendarProfile = InferSelectModel<typeof calendarProfiles>;
export type NewCalendarProfile = InferInsertModel<typeof calendarProfiles>;
